name = "karriers"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "karriers-db"
database_id = "bf2e5fdb-0c0f-4828-8efe-0351ded69940"
